version: "3.6"

services:
  app:
    image: traefik:v1.7.30-alpine
    # Note below that we use host mode to avoid source nat being applied to our ingress HTTP/HTTPS sessions
    # Without host mode, all inbound sessions would have the source IP of the swarm nodes, rather than the
    # original source IP, which would impact logging. If you don't care about this, you can expose ports the 
    # "minimal" way instead
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/data/config/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/data/config/traefik:/etc/traefik
      - /var/data/traefik/traefik.log:/traefik.log
      - /var/data/traefik/acme.json:/acme.json
    networks:
      - traefik_public
    # Global mode makes an instance of traefik listen on _every_ node, so that regardless of which
    # node the request arrives on, it'll be forwarded to the correct backend service.
    #extra_hosts:
        #- "thechances.us:192.168.1.254"
    deploy:
      mode: global
      labels:
        - traefik.frontend.rule=Host:traefik.thechances.us
        - traefik.port=8080   
        - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        - traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        - traefik.frontend.auth.forward.trustForwardHeader=true
        - traefik.docker.network=traefik_public
      placement:
        constraints: [node.role == manager]
    command: --web --docker --docker.swarmmode --docker.watch --docker.domain=thechances.us --logLevel=DEBUG
  traefik-forward-auth:
      image: thomseddon/traefik-forward-auth:2
      environment:
        - CLOUDFLARE_EMAIL=
        - CLOUDFLARE_API_KEY=
        - CLIENT_ID=502085016305-rokugm4pr2vrstuv8lq5brgulscu45lh.apps.googleusercontent.com
        - CLIENT_SECRET=gNo2vK3iSJSsP5Na3AZ5cOge
        - SECRET=uGlqxIDzAHDDI
        - INSECURE_COOKIE=false # Example assumes no https, do not use in production
        - AUTH_HOST=auth.thechances.us
        - WHITELIST=dnchance@gmail.com
        #- WHITELIST=jenniferchance26@gmail.com
        #- WHITELIST=lesleysimone06@gmail.com
      networks:
        - traefik_public
      #extra_hosts:
        #- "thechances.us:192.168.1.254"
      deploy:
        labels:
         - traefik.port=4181
         - traefik.frontend.rule=Host:auth.thechances.us
         - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
         - traefik.frontend.auth.forward.trustForwardHeader=true
networks:
  traefik_public:
    external: true

