version: '2.4'
services:
    wyze-bridge:
        container_name: wyze-bridge
        restart: always
        image: mrlt8/wyze-bridge:latest # Use a prebuilt image
        # build:  # Uncomment to build from source
        #     context: ./app # Uncomment to build from source
        #     # dockerfile: Dockerfile.arm # Uncomment to build for arm
        ports:
            - 1935:1935
            - 8554:8554
            - 8888:8888
        deploy:
          labels:
            - traefik.port=8888
            - traefik.frontend.rule=Host:radarr.thechances.us
            - traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
            - traefik.frontend.auth.forward.trustForwardHeader=true  
         environment:
            - WYZE_EMAIL=${WYZE_EMAIL} # Replace with wyze email 
            - WYZE_PASSWORD=${WYZE_PASSWORD} # Replace with wyze password
