version: "3"

services:
  app:
    image: portainer/portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/data/config/portainer:/data
    networks:
      - traefik_public
      - default
    deploy:
      labels:
        - traefik.frontend.rule=Host:portainer.thechances.us
        - traefik.port=9000
        #- traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181
        #- traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User
        #- traefik.frontend.auth.forward.trustForwardHeader=true
        - traefik.docker.network=traefik_public
      placement:
        constraints: [node.role == manager]
    command: -H unix:///var/run/docker.sock 
networks:
  traefik_public:
    external: true
  default:
    driver: overlay